{% set version = "1.1.0" %}

package:
  name: python-oauth2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-oauth2/python-oauth2-{{ version }}.tar.gz
  sha256: b24da812837c19183df1924e80a22ba0a1869582dea8b04a9ecd807b04dbc525

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - oauth2

about:
  home: https://github.com/wndhydrnt/python-oauth2
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'OAuth 2.0 provider written in python'

  description: |
    python-oauth2 is a framework that aims at making it easy to provide
    authentication via OAuth 2.0 within an application stack.
  doc_url: https://python-oauth2.readthedocs.io
  dev_url: https://github.com/wndhydrnt/python-oauth2

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
