travis:
  secure:
    BINSTAR_TOKEN: 47HNaIGjIEsD4BtvCMXhK+4xnUKoMuWrTwc4Fa3CATgiaGJY5TquF+fbN+G8MVVZugKORS4SC7iscBLBEb8ppbhfRSVPmTWsHq0z/uT8XusjOUp2FeOCJmdGuu/+dcZm//S8ZLxBzNGxZDDSVRy06RHtKfND/Y7nDvJ0kfCKS8UT1V/BXFX/7cyRuPgr+P3AiUNnsD3UC8BUONViCEIwGEcGO5cZGujpvWp0AbfyE9ctMWfFXDckk7O0IIITjsBkVf5DwBzvrHuQ1bFf1GmDlJEf4pUKKo76ECRj6DeOkqThy6tNlFDSwPQJ4siOZrnEG64JpSESTnr1ShpX3QJvCPvrGkkForAzR3/4GwaPBsoPM3vM16I72XhSix7ptanp5vK3JXX+gWhhZn38U639wESgpeH0bIkydijNgsMppkMWovRY9BwMUhdoQ8R9xJJX82Q1YNTfwe0r9G9qTr5wd4L8EVGN51+qVNyZQQ0dLYCe9pfnHyDU8cC+k8Zk7scgLKpNSbeL7kW1oJfSndYIBSIB1ry5kkQVmVYmnbUOaBfO9k00dHia7rw4E/iM3/6bn1oNWhv8DFY2Zoszeo462fppbzjg27abvHEFFPGLbVzSXL7clJV1oAbyN7PWWUBjd/tf+SipMUOkc8ybelxA+ceadQ6LwVBjHXn3EPX8bus=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
