travis:
  secure:
    BINSTAR_TOKEN: qJ4vMC1rzyVNxXr7kGuadsuLrvl9/ckseXsrtzDJHF61rAzvTliyTK31oFvX5sEzwJAdWObeie52upLpYpmUrdSdPP1WEhhGg5YEheD5PrmKJaorhdfjfjc0TU4UQCD9TvzRIuEs8PiCwx9IouXkpt/m3xj5TMkQmlFThs/3315bW8yC4rG5/ZppRXZzFSAa173yNPO22r0woaMuCmuGGd/Lg3AtzGirda/FvGhqOWc7yNsxLN8YNzO7d2i5y4/a2vZBKSiPuYzHXc2NP9CrQvzce10OBi1jVCkxKS3HE54p0mfVw5rVE1qPQsNww2XvFAHCAzEQm1b43mbp0vwGy16NzfQcvQO73bEYGG/dn79gFtHTti/YrQDZbY1HCeavSdkNeyHS9naAxUvLAJ9IbUhK6Ll/zI6UrWIIS02tRIYLXXpYf0QafWnzhMf0voawvYJWB3A6FffABa/EPYtkscXM5WFrxOWuHtM0jkYXKL1e2HGM7psty7J381ueSlkFGz7HayQX8VGsyf/P00ebWENTcr4sTQrLsRGttU0O5vwFPALuY8E5+j8FQ/KH1jkKH4166WACP9+ElYXZvT4oQOFcaMrDs3pP+aYTvW/2Eso8Bdkm/+dGGaBs5xOxv9duHKPUqk8qO6BH8nTYWEfmbXgUQvL95TZyfEYFX6f5MWc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
